language: python

sudo: required
cache: packages

python:
  - "3.6"

env:
  global:
    - SPARK_VERSION="2.4.0"
    - HADOOP_VERSION="2.7"
    - SPARK_PATH="spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}"
    - SPARK_HOME="/tmp/${SPARK_PATH}"
    - JAVA_VERSION=oraclejdk8
    - PATH="${PATH}:${SPARK_HOME}/bin"

before_install:
  - pip install --upgrade pip
  - curl -s https://raw.githubusercontent.com/dirmeier/spark-travis/master/setup_spark.sh | bash

install:
  - pip install -e '.[test]'
  - pip install codecov
  - pip install pytest-cov
  - pip install tox-travis

script:
  - spark-submit -h
  - py.test --cov=./ tests/test_pybda.py
  - py.test --cov=./ tests/test_kmeans.py
  - py.test --cov=./ tests/test_gmm.py
  - py.test --cov=./ tests/test_forest.py
  - py.test --cov=./ tests/test_gbm.py
  - py.test --cov=./ tests/test_glm.py
  - py.test --cov=./ tests/test_fa.py
  - py.test --cov=./ tests/test_ica.py
  - py.test --cov=./ tests/test_kpca.py
  - py.test --cov=./ tests/test_lda.py
  - py.test --cov=./ tests/test_pca.py
  - py.test --cov=./ tests/test_stats.py


after_success:
  - codecov
