
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.7

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            - v1-dependencies-

      - run:
          name: install java
          command: |
              sudo apt-get update
              sudo apt-get -y upgrade
              sudo apt-get install openjdk-8-jdk

      - run:
          name: install spark
          command: |
            export SPARK_VERSION='2.4.3'
            export HADOOP_VERSION='2.7'
            export SPARK_PATH="spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}"
            export SPARK_HOME="/tmp/${SPARK_PATH}"
            export PATH="${PATH}:${SPARK_HOME}/bin"
            cd /tmp && curl "http://mirror.easyname.ch/apache/spark/spark-${SPARK_VERSION}/${SPARK_PATH}.tgz" --output "${SPARK_HOME}.tgz" && tar -xvzf "${SPARK_HOME}.tgz"
            tar -xvzf "${SPARK_HOME}.tgz"

      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e '.[test]'
            pip install pytest-cov
            pip install tox-travis
            sudo pip install codecov

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}

      - run:
          name: run tests
          command: |
            export SPARK_VERSION='2.4.3'
            export HADOOP_VERSION='2.7'
            export SPARK_PATH="spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}"
            export SPARK_HOME="/tmp/${SPARK_PATH}"
            export JAVA_VERSION='oraclejdk8'
            export PATH="${PATH}:${SPARK_HOME}/bin"
            . venv/bin/activate
            py.test tests/test_fa.py
            py.test tests/test_forest.py
            py.test tests/test_gbm.py
            py.test tests/test_glm.py
            py.test tests/test_gmm.py
            py.test tests/test_ica.py
            py.test tests/test_kmeans.py
            py.test tests/test_kpca.py
            py.test tests/test_lda.py
            py.test tests/test_pca.py
            py.test tests/test_stats.py
            py.test --cov=./pybda/ tests/test_pybda.py

      - run:
          name: compute coverage
          command: |
            codecov

      - store_artifacts:
          path: test-reports
          destination: test-reports